services:
  pg_srv:
    image: "postgres:15.1-alpine3.17"
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - .env
    volumes:
      - pg_srv_data:/var/lib/postgresql/data
volumes:
  pg_srv_data:
    external: true
